export type SpectrumQuestion = {
  id: string;
  section: "how-we-roll" | "extra-spectrums";
  /** Shown before the question title in the card heading. */
  headingEmoji: string;
  title: string;
  leftLabel: string;
  rightLabel: string;
};

export const SECTION_LABELS: Record<SpectrumQuestion["section"], string> = {
  "how-we-roll": "How We Roll",
  "extra-spectrums": "Extra Spectrums",
};

export const QUESTIONS: SpectrumQuestion[] = [
  {
    id: "early-bird-night-owl",
    section: "how-we-roll",
    headingEmoji: "🌗",
    title: "Best Time of Day",
    leftLabel: "Early bird",
    rightLabel: "Night owl",
  },
  {
    id: "work-together-go-alone",
    section: "how-we-roll",
    headingEmoji: "👥",
    title: "Work Style",
    leftLabel: "Work on it together",
    rightLabel: "Go off alone and think",
  },
  {
    id: "backstory-cut-to-chase",
    section: "how-we-roll",
    headingEmoji: "📜",
    title: "Context Preference",
    leftLabel: "Tell me the backstory",
    rightLabel: "Cut to the chase",
  },
  {
    id: "interrupt-vs-slack",
    section: "how-we-roll",
    headingEmoji: "📣",
    title: "How to Reach Me",
    leftLabel: "Interrupt when you need me",
    rightLabel: "Slack/text",
  },
  {
    id: "no-schedule-standard-hours",
    section: "how-we-roll",
    headingEmoji: "🗓️",
    title: "Availability",
    leftLabel: "I have no schedule",
    rightLabel: "Standard hours",
  },
  {
    id: "tell-me-what-to-do-give-context",
    section: "how-we-roll",
    headingEmoji: "🎯",
    title: "Direction Style",
    leftLabel: "Just tell me what to do",
    rightLabel: "Give me all the context",
  },
  {
    id: "ship-vs-production",
    section: "how-we-roll",
    headingEmoji: "🚀",
    title: "Experimentation",
    leftLabel: "Not perfect enough to ship",
    rightLabel: "Let's try it in production!",
  },
  {
    id: "public-private-recognition",
    section: "how-we-roll",
    headingEmoji: "⭐",
    title: "Recognition Preference",
    leftLabel: "I prefer public recognition",
    rightLabel: "I prefer private recognition",
  },
  {
    id: "schedule-chat-video-chat",
    section: "how-we-roll",
    headingEmoji: "📹",
    title: "Conversation Preference",
    leftLabel: "Schedule time to chat",
    rightLabel: "Video chat",
  },
  {
    id: "movies",
    section: "extra-spectrums",
    headingEmoji: "🎬",
    title: "Movies",
    leftLabel: "Comedy & Romance",
    rightLabel: "Action & Sci-Fi",
  },
  {
    id: "reading",
    section: "extra-spectrums",
    headingEmoji: "📚",
    title: "Reading",
    leftLabel: "Fiction & Fantasy",
    rightLabel: "Non-fiction & Biographies",
  },
  {
    id: "culinary",
    section: "extra-spectrums",
    headingEmoji: "🍽️",
    title: "Culinary",
    leftLabel: "Master Chef",
    rightLabel: "Microwave Magician",
  },
  {
    id: "alien-encounter",
    section: "extra-spectrums",
    headingEmoji: "🛸",
    title: "Alien Encounter",
    leftLabel: "Make Contact",
    rightLabel: "Panic & Hide",
  },
  {
    id: "time-travel",
    section: "extra-spectrums",
    headingEmoji: "⏱️",
    title: "Time Travel",
    leftLabel: "Visit the Past",
    rightLabel: "Explore the Future",
  },
  {
    id: "dream-vehicle",
    section: "extra-spectrums",
    headingEmoji: "🏎️",
    title: "Dream Vehicle",
    leftLabel: "Flying Car",
    rightLabel: "Submarine Yacht",
  },
  {
    id: "mythical-vs-robot",
    section: "extra-spectrums",
    headingEmoji: "✨",
    title: "Companion Pick",
    leftLabel: "Mythical Creatures",
    rightLabel: "Robot Companions",
  },
];

export const EMOJI_CHOICES = [
  "😀",
  "😎",
  "🤖",
  "🥷",
  "🧙",
  "🧠",
  "🦾",
  "🦖",
  "🐙",
  "🐻",
  "🐼",
  "🦊",
  "🐸",
  "🐯",
  "🦄",
  "🐵",
  "🐧",
  "🦉",
  "🐳",
  "🐬",
  "🦥",
  "🪩",
  "🎸",
  "🎮",
  "🛰️",
  "🛸",
  "🌈",
  "🌮",
  "🍕",
  "🍣",
  "☕",
  "🧋",
  "🚀",
  "🏴‍☠️",
];
